from dept_class import Department
from dept_class import Professor
from dept_class import Course
from dept_class import Student
#Testcases
if __name__ == "__main__":


    dept1 = Department('ENTC')
    dept2 = Department('Mechanical')

    course1 = Course('VLSI','VIII','ENTC')
    course2 = Course('EDC','IV','ENTC')
    course3 = Course('SS','III','ENTC')
    course4 = Course('Physics','I','ENTC')
    course5 = Course('Microprocessor','V','ENTC')
    course6 = Course('BCS','VII','ENTC')
    course7 = Course('Maths','I','ENTC')
    course8 = Course('DME','VII','Mechanical')
    course9 = Course('RAAC','V','Mechanical')
    course10 = Course('MQC','VI','Mechanical')
    course11 = Course('EEE','III','Mechanical')
    course12 = Course('Robotics','VIII','Mechanical')
    course13 = Course('Thermal Engineering','IV','Mechanical')
    course14 = Course('HT','V','Mechanical')

    prof1 = Professor('Kishor',['EDC','VLSI'])
    prof2 = Professor('Vilas',['SS','VLSI'])
    prof3 = Professor('Ninad',['Physics','Maths','Microprocessor'])
    prof4 = Professor('Vallabh',['Robotics','MQC','Maths'])
    prof5 = Professor('Ajay',['HT','RAAC','MQC'])
    prof6 = Professor('Mihir',['EEE','DME','Physics'])

    stud = Student('Archis' , 4125 , 'BE','ENTC')
    stud1 = Student('Vikram',2122 , 'SE','ENTC')
    stud2 = Student('Arnav', 3170 , 'TE','ENTC')
    stud3 = Student('Vijay', 1962,'FE','ENTC')
    stud4 = Student('Soham', 2990,'SE','ENTC')
    stud5 = Student('Pranav', 3971,'TE','ENTC')
    stud6 = Student('Viraj', 4987,'BE','ENTC')
    stud7 = Student('Anil', 1910,'FE','ENTC')
    stud8 = Student('Girish',3861,'TE','ENTC')
    stud9 = Student('Vinit' , 4146 ,'BE', 'Mechanical')
    stud10 = Student('Dinesh',2091 , 'SE','Mechanical')
    stud11 = Student('Anand', 3683 , 'TE','Mechanical')
    stud12 = Student('Chinmay', 1500,'FE','Mechanical')
    stud13 = Student('Prasad', 2111,'SE','Mechanical')
    stud14 = Student('Ritesh', 3900,'TE','Mechanical')
    stud15 = Student('Parth', 4004,'BE','Mechanical')
    stud16 = Student('Siddhesh', 1991,'FE','Mechanical')
    stud17 = Student('Chirag',1144,'FE','Mechanical')

    print ('\n')
    print ('Students who are not enrolled')
    print ('-----------------------------')
    stud.enroll_to_course(course6)
    stud1.enroll_to_course(course3)
    stud2.enroll_to_course(course5)
    stud3.enroll_to_course(course4)
    stud4.enroll_to_course(course3)
    stud5.enroll_to_course(course5)
    stud6.enroll_to_course(course6)
    stud7.enroll_to_course(course4)
    stud3.enroll_to_course(course7)
    stud8.enroll_to_course(course5)
    stud9.enroll_to_course(course8)
    stud10.enroll_to_course(course11)
    stud11.enroll_to_course(course9)
    stud12.enroll_to_course(course4)
    stud13.enroll_to_course(course11)
    stud14.enroll_to_course(course14)
    stud15.enroll_to_course(course8)
    stud16.enroll_to_course(course7)
    stud17.enroll_to_course(course7)
    

    print ('\n')
    print ('Department Details')
    print ('------------------')
    print (dept1)
    print (dept2)

    print ('\n')
    print ('Course Details')
    print ('--------------')
    print (course1)
    print (course2)
    print (course3)
    print (course4)
    print (course5)
    print (course6)
    print (course7)
    print (course8)
    print (course9)
    print (course10)
    print (course11)
    print (course12)
    print (course13)
    print (course14)

    print ('\n')
    print ('Professor Details')
    print ('----------------')
    print (prof1)
    print (prof2)
    print (prof3)
    print (prof4)
    print (prof5)
    print (prof6)

    print ('\n')
    print ('Students Details')
    print ('----------------')
    print (stud1)
    print (stud)
    print (stud2)
    print (stud3)
    print (stud4)
    print (stud5)
    print (stud6)
    print (stud7)
    print (stud8)  
    print (stud9)
    print (stud10)
    print (stud11)
    print (stud12)
    print (stud13)
    print (stud14)
    print (stud15)
    print (stud16)
    print (stud17)